### ISSUE TITLE
package prefix

### ISSUE THREAD

**Issue by shogg** [jordan-bonecutter/goption#5]
Hello all,

Only my biased opinion. In the README.md, in the examples, you should prefix all types and functions with the package name `goption`. Because that's how the code is used. The same applies to (black box) tests. Put them in `goption_test` to enforce the use of the package name, so tests become some kind of documentation on how to use the lib. Test cases then can cover and show intended use cases.

**Comment by jordan-bonecutter** [comment]
Keeping them as they are in favor of brevity

**Comment by shogg** [comment]
Good luck with leaving out the package name for brevity.
